### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by ihedzde** [ihedzde/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by ivangn03** [comment]
I'm feel like anxious procrastinator, gonna take a nap 😴.

**Comment by ivangn03** [comment]
I feel like a anxious procrastinator, gonna take a nap😴.

**Comment by ihedzde** [comment]
### I'm the head boss demon of the Procrastination department. I have 88% of the human workforce in my control.

**Comment by ihedzde** [comment]
### Résumé
I'm the head boss demon of the Procrastination department. I have 88% of the human workforce in my control.
