### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by ihedzde** [ihedzde/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by ivangn03** [comment]
I feel like a fun procrastinator, gonna restructure my TODO list.

**Comment by ihedzde** [comment]
# [🔗](#bushyasta) Bushyasta
* [Insta @procrasty_demon](https://www.instagram.com/procrasty_demon/)
* Phone +7762727846283
