### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by ihedzde** [ihedzde/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by ivangn03** [comment]
I feel like a  “Plenty of Time” Procrastinator, gonna reset my deadlines and stick to them.

**Comment by ihedzde** [comment]
## [🔗 ](#experience) EXPERIENCE
2021
Help my buddy Lil Nas X make and promote his new hit MONTERO.

2020
The most productive year of my whole life! With little help from my good friend Plague made people stay at home and download TikTok and procrastinate all day long.

2019
Took the UK by the storm. Helped Queen Elizabeth make her first-ever Instagram post making a bunch of people leave their tasks and mindlessly scroll through Instagram. 

2018
Won a huge fight with the Climate Change demon, made him slow down a little bit, cause I needed people to live doing nothing. Got a promotion: became the head boss demon of the Procrastination department.

2017
Enjoyed the Twitter hysteria made by Donal Trump. Making reading Twitter a top priority for Americans and not doing their job.

2016
Launched TikTok ♪. Started improving its algorithms.

2015
Recommended to create a Twitter account for Donal Trump. Got promotion in hell.

2014
After graduation got into the Procrastination department as an intern.
