### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by ihedzde** [ihedzde/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by ivangn03** [comment]
I feel like a perfectionist procrastinator, gonna leave that task up to you.

**Comment by ihedzde** [comment]
### [🔗](#hobies) HOBIES
* In my free time I like to create👩🏻‍💻 fast growing popular social media companies for humans procrastination. 
* As a high-ranking demon, I regularly invest in the entertainment industry🎬🎮 stocks 📈. 
### [🔗](#languages) LANGUAGES
I know every verbal and not verbal language on Earth 🌍.
### [🔗](#skills) SKILLS
* Making people lazy😩
* Make more work for PMs😡
* Burning deadlines🔥 📆
### [🔗](#likes) LIKES 😁
*  My favorite social media is obviously TikTok ♪ for which I was an inspiration 🥰. 
*  My favorite quote is from "Office"🏢: "I'm never going to do something, but if it helps others to do nothing, I'll do it to get nothing eventually would be done.".
* My friend calls me “evil genius” 😈🤓.
### [🔗](#dislikes) DISLIKES 😞
* When humans get their job done.✅
* Finished milestones.🏁
* Waking up in the morning. 🌄

**Comment by ihedzde** [comment]
Nice job 😅 👍🏻.
